### ISSUE TITLE
There is a card icon in the menu bar

### ISSUE THREAD

**Issue by jjqper** [vsta2018/hackintosh#1]
Thanks for the hard work. There is a card icon in the menu bar. If you click "Close Card", the computer will restart immediately. How to solve it?

**Comment by vsta2018** [comment]
Hello there,Thanks for bringing that up, I forgot to mention in the README about that!I have the exact same issue that you found, which I suspect there is a piece of hardware that the Elitebook 840 G6 has and the actual Mac Book Pro doesn’t: which is the WWAN interface (little slot on the right edge beside the headphone jack). Although the hardware is detected on newer version of macOS (Ventura, Sonoma), but I’m not using it! I didn’t see it in Monterey thoughI’ve tried to look into the bios see if I can disable it, but couldn’t find any option would allow me to do thatI recommend that you just ignore it (i.e.: not touch it)Just another note: I found Monterey is most stable with this laptop! Next is Sonoma, and Ventura is worst of the 3. And if you want to … not see it, try to use Monterey instead. You would have to make change to the kext folder though! Top of my head would be airportitlwm, there may be others.Hope you enjoy it.From:  Jack ***@***.***>Date:  Friday, March 29, 2024 at 11:32 AMTo:  vsta2018/hackintosh ***@***.***>Cc:  Subscribed ***@***.***>Subject:  [vsta2018/hackintosh] There is a card icon in the menu bar (Issue #1)
Thanks for the hard work. There is a card icon in the menu bar. If you click "Close Card", the computer will restart immediately. How to solve it?

**Comment by jjqper** [comment]
Thank you very much for your timely message, it has been of great help and inspiration to me. I will try Mentery and compare it with Ventura. However, I would like to remind you here that there is also an EFI file on Github (the address is as follows: https://github.com/yusufklncc/HP-EliteBook-840-G6-Hackintosh/tree/main), but it does not have a menu bar card. icon, but its EFI can only be run on a USB flash drive. Once copied to the hard disk and run away from the USB flash drive, the computer will freeze. Do you have the time and interest to research this? Thanks again and my heartfelt respect to you!

**Comment by jjqper** [comment]
Thank you very much for your timely message, it has been of great help and inspiration to me. I will try Mentery and compare it with Ventura. However, I would like to remind you here that there is also an efi file on Github (the address is as follows: https://github.com/yusufklncc/HP-EliteBook-840-G6-Hackintosh/tree/main), but it does not have a menu bar card. icon, but its EFI can only be run on a USB flash drive. Once copied to the hard disk and run away from the USB flash drive, the computer will freeze. Do you have the time and interest to research this? Thanks again and my heartfelt respect to you!

**Comment by vsta2018** [comment]
> Thank you very much for your timely message, it has been of great help and inspiration to me. I will try Mentery and compare it with Ventura. However, I would like to remind you here that there is also an efi file on Github (the address is as follows: https://github.com/yusufklncc/HP-EliteBook-840-G6-Hackintosh/tree/main), but it does not have a menu bar card. icon, but its EFI can only be run on a USB flash drive. Once copied to the hard disk and run away from the USB flash drive, the computer will freeze. Do you have the time and interest to research this? Thanks again and my heartfelt respect to you!

@jjqper,

Thanks for bringup that repo. I've combined the content of my ACPI folder with that of the above mentioned repo, which in turn add the following files to the ACPI folder:

-  SSDT-ALS0.aml
-  SSDT-HPET.aml
-  SSDT-SBUS-MCHC.aml
-  SSDT-TB3.aml

And that seems to resolve the issue on my machine. I've also updated my repo with the new change.

Happy Hackintoshing!
